# Generated by Django 4.1.1 on 2022-09-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=8, max_length=255),
            preserve_default=False,
        ),
    ]
